#!/bin/bash

# Check if both arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Missing file or hash in the command."
    echo "Usage: md5check <file> <hash>"
    exit 1
fi

# Get the file name and hash from command-line arguments
file=$1
expected_hash=$2

# Check if the file exists
if [ ! -f "$file" ]; then
    echo "The file '$file' does not exist."
    exit 1
fi

# Get the hash of the file
computed_hash=$(md5sum "$file" | awk '{print $1}')

# Compare the hashes
if [ "$computed_hash" = "$expected_hash" ]; then
    echo "------------"
    echo "Hashes match"
    echo "------------"
else
    echo "-------------------"
    echo "Hashes do not match"
    echo "-------------------"

fi